server:
  port: ${SERVER_PORT:8083}
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:wuhu_test}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:127814}
  redis:
    host: ${REDIS_HOST:127.0.0.1} #服务地址
    port: ${REDIS_PORT:6379} #服务器连接端口
    pool:
      maxTotal: 30 #连接池最大连接数(使用负值表示没有限制)
      maxWaitMillis: 1800 #连接池最大阻塞时间(使用负值表示没有限制)
      maxIdle: 20 #连接池中最大空闲连接
      minIdle: 1 #连接池中最下空闲连接
    cacheTime: ${REDIS_CACAETIME:86400} #有效周期1天

mybatis:
    type-aliases-package: net.sunrise.wh.userserver.domain
    mapper-locations: classpath:mybatis/mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
