server:
  port: 8083
spring:
  application:
    name: gs-user
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.10.238}:${MYSQL_PORT:3306}/${MYSQL_DB:gs_test}?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:123456}
  redis:
    host: ${REDIS_HOST:192.168.10.238} #服务地址
    port: ${REDIS_PORT:6381} #服务器连接端口
    pool:
      maxTotal: 30 #连接池最大连接数(使用负值表示没有限制)
      maxWaitMillis: 1800 #连接池最大阻塞时间(使用负值表示没有限制)
      maxIdle: 20 #连接池中最大空闲连接
      minIdle: 1 #连接池中最下空闲连接
    cacheTime: 86400 #有效周期1天

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8081}/eureka/
  instance:
    prefer-ip-address: true

mybatis:
    type-aliases-package: net.sunrise.gs.domain
    mapper-locations: classpath:mybatis/mapper/*.xml

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
env: 
  test

